# Generated by Django 2.0.2 on 2021-04-12 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_product_video'),
        ('offer', '0007_conditionaloffer_exclusive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponDistributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cdn', models.CharField(max_length=20, unique=True)),
                ('uin', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=16, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_address', models.TextField(blank=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRangeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_rng', models.CharField(choices=[('10000-50000', '10k to 50k'), ('50000-80000', '50k to 80k'), ('80000-100000', '80k to 1 lac'), ('100000-150000', '1 lac to 1.5 lac'), ('150000-200000', '1.5 lac to 2 lac')], max_length=25)),
                ('discount_type', models.CharField(choices=[('Percentage', "Discount is a percentage off of the product's value"), ('Absolute', "Discount is a fixed amount off of the product's value")], default='Percentage', max_length=128)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category')),
            ],
        ),
    ]
