# Generated by Django 2.0.2 on 2021-04-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_coupondistributor_pricerangemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupondistributor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coupondistributor',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pricerangemodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pricerangemodel',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
