# Generated by Django 2.0.2 on 2021-04-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_auto_20210412_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupondistributor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricerangemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
