# Generated by Django 2.0.2 on 2021-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_auto_20210414_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupondistributor',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='coupondistributor',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
