# Generated by Django 2.0.2 on 2021-04-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_auto_20210419_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='min_billing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
