# Generated by Django 2.0.2 on 2021-04-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_range_min_billing_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='coupon_distibutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.CouponDistributor'),
        ),
    ]
