# Generated by Django 2.0.2 on 2021-04-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0006_auto_20180413_0911'),
        ('catalogue', '0058_auto_20210414_1207'),
        ('offer', '0013_range_coupon_distibutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeCouponModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Start datetime')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End datetime')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category')),
                ('range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.Range')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.Voucher')),
            ],
        ),
    ]
