# Generated by Django 2.0.2 on 2021-04-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_customizecouponmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizecouponmodel',
            name='coupon_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
