# Generated by Django 2.0.2 on 2021-04-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_customizecouponmodel_coupon_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='type',
            field=models.CharField(blank=True, choices=[('Percentage', "Discount is a percentage off of the product's value"), ('Absolute', "Discount is a fixed amount off of the product's value"), ('Multibuy', 'Discount is to give the cheapest product for free'), ('Fixed price', 'Get the products that meet the condition for a fixed price'), ('Shipping absolute', 'Discount is a fixed amount of the shipping cost'), ('Shipping fixed price', 'Get shipping for a fixed price'), ('Shipping percentage', 'Discount is a percentage off of the shipping cost'), ('Customizeprice', "Discount is a customize off of the product's value")], max_length=128, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='pricerangemodel',
            name='price_rng',
            field=models.CharField(choices=[('15000-49999', '15,000 - 49,999'), ('20000-49999', '20,000 - 49,999'), ('30000-69999', '30,000 - 69,999'), ('50000-74999', '50,000 - 74,999'), ('50000-79999', '50,000 - 79,999'), ('70000-99999', '70,000 - 99,999'), ('75000-99999', '75,000 - 99,999'), ('80000-99999', '80,000 - 99,999'), ('100000-149999', '1,00,000 - 1,49,999'), ('150000-199999', '1,50,000 - 1,99,999'), ('200000-1000000', '2,00,000 Onwards')], max_length=25),
        ),
    ]
