# Generated by Django 2.0.2 on 2021-05-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0017_customizecouponmodel_used_coupon_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizecouponmodel',
            name='used_coupon_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
