# Generated by Django 2.0.2 on 2021-06-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0019_auto_20210603_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerangemodel',
            name='price_rng',
            field=models.CharField(choices=[('1-1999', 'Below 1,999'), ('2000-4999', '2,000 - 4,999'), ('5000-6999', '5,000 - 6,999'), ('7000-9999', '7,000 - 9,999'), ('10000-24999', '10,000 - 24,999'), ('25000-1000000', 'Above 25,000')], max_length=25),
        ),
    ]
