# Generated by Django 2.0.2 on 2020-03-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
