# Generated by Django 2.0.2 on 2020-04-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200316_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
