# Generated by Django 2.0.2 on 2020-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
