# Generated by Django 2.0.2 on 2020-12-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_enquiry_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
