# Generated by Django 2.0.2 on 2020-12-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_auto_20201106_1900'),
        ('customer', '0013_enquiry_enquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(1, 'Annual'), (2, 'Festival'), (3, 'Concert'), (4, 'Exhibition'), (5, 'Fashion Show'), (6, 'Customized Wedding'), (7, 'Customized Birthday'), (8, 'Other')], default=1),
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='allocated_vendor',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='allocated_vendor',
            field=models.ManyToManyField(blank=True, null=True, to='partner.Partner'),
        ),
    ]
