# Generated by Django 2.0.2 on 2020-12-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20201208_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='event_type',
            field=models.CharField(choices=[('1', 'Annual'), ('2', 'Festival'), ('3', 'Concert'), ('4', 'Exhibition'), ('5', 'Fashion Show'), ('6', 'Customized Wedding'), ('7', 'Customized Birthday'), ('8', 'Other')], max_length=50),
        ),
    ]
