# Generated by Django 2.0.2 on 2020-12-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_basket_customized_basket'),
        ('customer', '0016_auto_20201210_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='basket_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_basket', to='basket.Basket'),
        ),
    ]
