# Generated by Django 2.0.2 on 2020-12-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_enquiry_basket_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='allocated_vendor',
            field=models.ManyToManyField(blank=True, to='partner.Partner'),
        ),
    ]
