# Generated by Django 2.0.2 on 2020-12-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20201218_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='allocated_vendor',
            field=models.ManyToManyField(blank=True, null=True, to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='budget_from',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='budget_to',
            field=models.PositiveIntegerField(),
        ),
    ]
