# Generated by Django 2.0.2 on 2021-04-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20201224_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('mobile_number', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=100)),
                ('sms_response', models.TextField(blank=True, null=True)),
                ('otp_attempt_count', models.IntegerField(blank=True, null=True)),
                ('otp_sent_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
