# Generated by Django 2.0.2 on 2021-05-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_otpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp_attempt_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
