# Generated by Django 2.0.6 on 2018-07-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20180718_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='booking_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='booking_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
