# Generated by Django 2.0.2 on 2020-11-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20180718_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='product_attributes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
