# Generated by Django 2.0.2 on 2020-12-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_line_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='customized_basket',
            field=models.BooleanField(default=False),
        ),
    ]
