# Generated by Django 2.0.2 on 2021-03-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_basket_customized_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='flower_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
