# Generated by Django 2.0.2 on 2021-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_line_flower_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='is_package_product',
            field=models.BooleanField(default=False),
        ),
    ]
