# Generated by Django 2.0.6 on 2018-08-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_customcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCategory',
        ),
    ]
