# Generated by Django 2.0.2 on 2020-03-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_delete_customcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_sequence',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
