# Generated by Django 2.0.2 on 2020-03-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_productimage_image_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_product_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('image_product_sequence', 'product')},
        ),
    ]
