# Generated by Django 2.0.2 on 2020-03-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20200304_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='img_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
