# Generated by Django 2.0.2 on 2020-03-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_productimage_is_dp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='master_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
