# Generated by Django 2.0.2 on 2020-04-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_category_master_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_combo_product',
            field=models.BooleanField(default=False),
        ),
    ]
