# Generated by Django 2.0.2 on 2020-04-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_product_is_combo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='combo_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='combo_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
