# Generated by Django 2.0.2 on 2020-04-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20200427_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product_title', models.CharField(blank=True, max_length=255, null=True)),
                ('combo_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_product', to='catalogue.Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_child_product', to='catalogue.Product')),
            ],
        ),
    ]
