# Generated by Django 2.0.2 on 2020-10-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_comboproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_product_category', to='catalogue.Category')),
                ('product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_1', to='catalogue.Product')),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='catalogue.Product')),
                ('product3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_3', to='catalogue.Product')),
                ('product4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_4', to='catalogue.Product')),
                ('product5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_5', to='catalogue.Product')),
                ('product6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_6', to='catalogue.Product')),
                ('product7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_7', to='catalogue.Product')),
                ('product8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_8', to='catalogue.Product')),
                ('product9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_9', to='catalogue.Product')),
            ],
        ),
    ]
