# Generated by Django 2.0.2 on 2020-10-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_premiumproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboProductsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('combo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('combo_product', models.ManyToManyField(to='catalogue.Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_products', to='catalogue.Product')),
            ],
        ),
    ]
