# Generated by Django 2.0.2 on 2020-10-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_comboproductsmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproductsmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
