# Generated by Django 2.0.2 on 2020-10-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_comboproductsmaster_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumproducts',
            name='product1',
        ),
        migrations.RemoveField(
            model_name='premiumproducts',
            name='product2',
        ),
        migrations.RemoveField(
            model_name='premiumproducts',
            name='product3',
        ),
        migrations.RemoveField(
            model_name='premiumproducts',
            name='product4',
        ),
        migrations.RemoveField(
            model_name='premiumproducts',
            name='product5',
        ),
        migrations.RemoveField(
            model_name='premiumproducts',
            name='product6',
        ),
        migrations.RemoveField(
            model_name='premiumproducts',
            name='product7',
        ),
        migrations.RemoveField(
            model_name='premiumproducts',
            name='product8',
        ),
        migrations.RemoveField(
            model_name='premiumproducts',
            name='product9',
        ),
        migrations.AddField(
            model_name='premiumproducts',
            name='product',
            field=models.ManyToManyField(to='catalogue.Product'),
        ),
    ]
