# Generated by Django 2.0.2 on 2020-11-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20201028_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproductsmaster',
            name='round_combo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='comboproductsmaster',
            name='upc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comboproductsmaster',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_products', to='catalogue.Product'),
        ),
        migrations.AlterField(
            model_name='comboproductsmaster',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
