# Generated by Django 2.0.2 on 2020-11-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_auto_20201031_1343'),
        ('catalogue', '0020_auto_20201103_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproductsmaster',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comboproductsmaster',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comboproductsmaster',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_vendor', to='partner.Partner'),
        ),
    ]
