# Generated by Django 2.0.2 on 2020-11-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20201103_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboProductsMasterProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comboproductsmaster',
            name='combo_product',
            field=models.ManyToManyField(blank=True, to='catalogue.Product'),
        ),
        migrations.AddField(
            model_name='comboproductsmasterproducts',
            name='combo_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_offers', to='catalogue.ComboProductsMaster'),
        ),
        migrations.AddField(
            model_name='comboproductsmasterproducts',
            name='combo_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm_product', to='catalogue.Product'),
        ),
    ]
