# Generated by Django 2.0.2 on 2020-11-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20201105_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproductsmaster',
            name='max_allowed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
