# Generated by Django 2.0.2 on 2020-11-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_product_daily_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deposite_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deposite_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
