# Generated by Django 2.0.2 on 2020-11-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20201109_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_transporation_available',
            field=models.BooleanField(default=False),
        ),
    ]
