# Generated by Django 2.0.2 on 2020-11-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_auto_20201106_1900'),
        ('catalogue', '0026_product_is_transporation_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCostEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product_upc', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_from', models.PositiveIntegerField()),
                ('quantity_to', models.PositiveIntegerField()),
                ('requirement_day', models.PositiveIntegerField()),
                ('cost_incl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transport_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_transport', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cost_entries', to='catalogue.Product')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product_cost_entries', to='partner.Partner')),
            ],
        ),
    ]
