# Generated by Django 2.0.2 on 2020-11-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_productcostentries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('apply_to', models.CharField(choices=[('1', 'For all rental products'), ('2', 'For all selling products'), ('3', 'For few products')], max_length=255)),
                ('products', models.ManyToManyField(blank=True, to='catalogue.Product')),
            ],
        ),
    ]
