# Generated by Django 2.0.2 on 2020-11-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_auto_20201126_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcostentries',
            name='quantity_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcostentries',
            name='quantity_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcostentries',
            name='requirement_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
