# Generated by Django 2.0.2 on 2020-12-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_auto_20201203_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcostentries',
            name='rent_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
