# Generated by Django 2.0.2 on 2020-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_productcostentries_rent_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
