# Generated by Django 2.0.2 on 2020-12-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_auto_20201217_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_tax_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
