# Generated by Django 2.0.2 on 2021-01-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_quantity_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
