# Generated by Django 2.0.2 on 2021-01-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_product_is_quantity_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rent_transportation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_transportation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
