# Generated by Django 2.0.2 on 2021-01-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0041_auto_20210104_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_meta_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_title_meta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
