# Generated by Django 2.0.2 on 2021-01-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_product_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_booking_time_delay',
            field=models.IntegerField(blank=True, default=48, max_length=255, null=True),
        ),
    ]
