# Generated by Django 2.0.2 on 2021-01-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_product_product_booking_time_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_booking_time_delay',
            field=models.IntegerField(blank=True, default=48, null=True),
        ),
    ]
