# Generated by Django 2.0.2 on 2021-01-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0045_auto_20210114_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxation',
            name='sale_tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
