# Generated by Django 2.0.2 on 2021-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_taxation_sale_tax_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_frontside',
            field=models.BooleanField(default=True),
        ),
    ]
