# Generated by Django 2.0.2 on 2021-01-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_category_show_on_frontside'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedPayPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('advance_payment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('apply_to', models.CharField(choices=[('1', 'For all rental products'), ('2', 'For all selling products'), ('3', 'For all rent and sale products'), ('4', 'For all professional products')], max_length=255)),
            ],
        ),
    ]
