# Generated by Django 2.0.2 on 2021-02-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_advancedpaypercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesWiseFilterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category')),
            ],
        ),
        migrations.CreateModel(
            name='FilterValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='categorieswisefiltervalue',
            name='filter_name',
            field=models.ManyToManyField(blank=True, to='catalogue.FilterValues'),
        ),
    ]
