# Generated by Django 2.0.2 on 2021-02-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_auto_20210203_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieswisefiltervalue',
            name='filter_names',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
