# Generated by Django 2.0.2 on 2021-02-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0050_categorieswisefiltervalue_filter_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedpaypercentage',
            name='sale_advance_payment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
