# Generated by Django 2.0.2 on 2021-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0051_advancedpaypercentage_sale_advance_payment_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, default='image_not_found.jpg', max_length=255, null=True, upload_to='header_menu/category_icon/'),
        ),
        migrations.AddField(
            model_name='category',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='image_not_found.jpg', max_length=255, null=True, upload_to='header_menu/category_img/'),
        ),
    ]
