# Generated by Django 2.0.2 on 2021-03-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_product_is_featured_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_icons',
            field=models.FileField(blank=True, default='image_not_found.jpg', max_length=255, null=True, upload_to='header_menu/show_in_icon/'),
        ),
    ]
