# Generated by Django 2.0.2 on 2021-03-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_category_show_in_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_artificial_flower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_real_flower',
            field=models.BooleanField(default=False),
        ),
    ]
