# Generated by Django 2.0.2 on 2021-03-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_auto_20210317_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_video_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
