# Generated by Django 2.0.2 on 2021-03-25 11:26

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_product_youtube_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
