# Generated by Django 2.0.2 on 2021-04-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0058_auto_20210414_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_caption',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
