# Generated by Django 2.0.2 on 2021-05-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0059_productimage_image_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesWisePriceFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_value', models.PositiveIntegerField(blank=True, null=True)),
                ('to_value', models.PositiveIntegerField(blank=True, null=True)),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category')),
            ],
        ),
    ]
