# Generated by Django 2.0.2 on 2021-06-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0060_categorieswisepricefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_package',
            field=models.ManyToManyField(blank=True, null=True, related_name='package_product', to='catalogue.Product'),
        ),
    ]
