# Generated by Django 2.0.2 on 2022-10-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0061_auto_20210610_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_alt_text',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
