# Generated by Django 2.0.6 on 2018-08-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180724_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='total_amount_incl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
