# Generated by Django 2.0.2 on 2020-03-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20180808_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCavenuePaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'CC Avenue Payment',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ccavenuepaymentdetails',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_order', to='order.Order'),
        ),
    ]
