# Generated by Django 2.0.2 on 2020-03-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200309_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccavenuepaymentdetails',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_status',
            field=models.CharField(blank=True, choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=100, null=True),
        ),
    ]
