# Generated by Django 2.0.2 on 2020-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200318_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccavenuepaymentdetails',
            name='gateway_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ccavenuepaymentdetails',
            name='payment_reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ccavenuepaymentdetails',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='initiated', max_length=100),
        ),
    ]
