# Generated by Django 2.0.2 on 2020-03-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200319_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccavenuepaymentdetails',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancel', 'Cancel'), ('invalid', 'Invalid')], default='initiated', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_status',
            field=models.CharField(blank=True, choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancel', 'Cancel'), ('invalid', 'Invalid')], max_length=100, null=True),
        ),
    ]
