# Generated by Django 2.0.2 on 2020-03-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200319_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccavenuepaymentdetails',
            name='gateway_chiper',
            field=models.TextField(blank=True, null=True),
        ),
    ]
