# Generated by Django 2.0.2 on 2020-11-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_ccavenuepaymentdetails_gateway_chiper'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
    ]
