# Generated by Django 2.0.2 on 2020-11-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20201109_1522'),
        ('partner', '0013_auto_20201106_1900'),
        ('order', '0014_order_is_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAllocatedVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_order', to='order.Order')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='allocated_vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderallocatedvendor',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_order_line', to='order.Line'),
        ),
        migrations.AddField(
            model_name='orderallocatedvendor',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_product', to='catalogue.Product'),
        ),
        migrations.AddField(
            model_name='orderallocatedvendor',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_category', to='catalogue.Category'),
        ),
        migrations.AddField(
            model_name='orderallocatedvendor',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_order_vendor', to='partner.Partner'),
        ),
    ]
