# Generated by Django 2.0.2 on 2020-11-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20201119_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='final_payment',
            field=models.BooleanField(default=False),
        ),
    ]
