# Generated by Django 2.0.2 on 2020-11-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_line_final_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='product_attributes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
