# Generated by Django 2.0.2 on 2020-12-04 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_custombillingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombillingaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_billing', to=settings.AUTH_USER_MODEL),
        ),
    ]
