# Generated by Django 2.0.2 on 2020-12-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20201204_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='product_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='line',
            name='product_margin_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='order_margin_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
