# Generated by Django 2.0.2 on 2020-12-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20201209_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.CustomBillingAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_billing_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
