# Generated by Django 2.0.2 on 2021-01-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20201228_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
