# Generated by Django 2.0.2 on 2021-02-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_order_order_cancelled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('charges_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('apply_to', models.CharField(choices=[('1', 'Before 1 Month'), ('2', 'Before 15 Days'), ('3', 'Before 5 Days'), ('4', 'On the Event Date')], max_length=255)),
            ],
        ),
    ]
