# Generated by Django 2.0.2 on 2021-04-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_cancellationcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='is_line_package_product',
            field=models.BooleanField(default=False),
        ),
    ]
