# Generated by Django 2.0.6 on 2018-08-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20180717_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='country.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='country.State', verbose_name='State'),
        ),
    ]
