# Generated by Django 2.0.6 on 2018-08-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20180802_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
