# Generated by Django 2.0.2 on 2020-02-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_vendorcalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='gst_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='shop_act_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
