# Generated by Django 2.0.2 on 2020-03-12 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_productunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.ProductUnit'),
        ),
    ]
