# Generated by Django 2.0.2 on 2020-10-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20201028_1527'),
        ('partner', '0010_auto_20200417_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('backup1', models.ManyToManyField(related_name='backup1', to='partner.Partner')),
                ('backup2', models.ManyToManyField(related_name='backup2', to='partner.Partner')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_category', to='catalogue.Category')),
                ('frontliener', models.ManyToManyField(related_name='Backup_frontliener', to='partner.Partner')),
            ],
        ),
    ]
