# Generated by Django 2.0.2 on 2020-10-31 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20201028_1527'),
        ('partner', '0011_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_category', to='catalogue.Category')),
                ('individual_asp', models.ManyToManyField(related_name='individual_asp', to='partner.Partner')),
            ],
        ),
        migrations.RenameModel(
            old_name='Backup',
            new_name='MultiDB',
        ),
    ]
