# Generated by Django 2.0.2 on 2020-11-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_auto_20201031_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multidb',
            name='frontliener',
            field=models.ManyToManyField(related_name='Backup_frontliener', to='partner.Partner', verbose_name='Frontliner'),
        ),
    ]
