# Generated by Django 2.0.2 on 2020-12-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_auto_20201106_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='digital_signature',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_digital_signature/'),
        ),
    ]
