# Generated by Django 2.0.2 on 2020-12-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_partner_digital_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product_status', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors_name', to='partner.Partner')),
            ],
        ),
    ]
