# Generated by Django 2.0.2 on 2021-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_vendorproductstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='rent_transportation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='sale_transportation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
