# Generated by Django 2.0.2 on 2021-02-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0017_stockrecord_sale_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='sale_advance_payment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
