# Generated by Django 2.0.2 on 2021-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0018_stockrecord_sale_advance_payment_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='art_rent_market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='art_rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='art_rent_price_with_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='art_rent_round_off_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='art_rent_total_saving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='art_rent_transportation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='art_sale_market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='art_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='art_sale_price_with_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='art_sale_round_off_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='art_sale_total_saving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='art_sale_transportation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
