# Generated by Django 2.0.2 on 2021-01-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('RentCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFlatPages',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
