# Generated by Django 2.0.2 on 2021-01-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCore', '0004_abandonedcartlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customflatpages',
            name='page_type',
            field=models.CharField(blank=True, choices=[('0', 'Legal Documents'), ('1', 'Policies'), ('2', 'Terms and Conditions'), ('3', 'FAQ')], max_length=200, null=True),
        ),
    ]
