# Generated by Django 2.0.2 on 2021-01-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCore', '0005_auto_20210106_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customflatpages',
            name='page_type',
            field=models.CharField(blank=True, choices=[('0', 'Legal Documents'), ('1', 'Policies'), ('2', 'Terms and Conditions'), ('3', 'FAQ'), ('4', 'About Us'), ('5', 'How It Works')], max_length=200, null=True),
        ),
    ]
