# Generated by Django 2.0.6 on 2018-08-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_HeaderMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=225)),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeaderMenu.Admin_Header', verbose_name='title_id')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_HeaderSubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_menu_title', models.CharField(blank=True, max_length=225)),
                ('url', models.CharField(blank=True, max_length=225)),
                ('header_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeaderMenu.Admin_HeaderMenu')),
            ],
        ),
    ]
