# Generated by Django 2.0.2 on 2018-09-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeaderMenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_header',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
