# Generated by Django 2.0.2 on 2019-02-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeaderMenu', '0003_image_field_added_header_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_headermenu',
            name='menu_image',
            field=models.ImageField(blank=True, default='media/image_not_found.jpg', max_length=255, null=True, upload_to='header_menu/'),
        ),
    ]
