# Generated by Django 2.0.2 on 2019-02-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeaderMenu', '0004_image_field_added_header_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_headermenu',
            name='menu_image',
            field=models.ImageField(blank=True, default='image_not_found.jpg', max_length=255, null=True, upload_to='header_menu/'),
        ),
        migrations.AlterField(
            model_name='admin_headersubmenu',
            name='menu_image',
            field=models.ImageField(blank=True, default='image_not_found.jpg', max_length=255, null=True, upload_to='header_menu/'),
        ),
    ]
