# Generated by Django 2.0.2 on 2020-11-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_product_daily_capacity'),
        ('HeaderMenu', '0005_auto_20190219_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(blank=True, max_length=225)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('header_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeaderMenu.Admin_HeaderMenu')),
                ('product', models.ManyToManyField(to='catalogue.Product')),
            ],
        ),
    ]
