# Generated by Django 2.0.2 on 2020-11-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeaderMenu', '0007_managemenumasterproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_menu',
            name='header_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeaderMenu.Admin_Header'),
        ),
    ]
