# Generated by Django 2.0.2 on 2021-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='cta_button_text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='is_provide_path_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='path_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
