# Generated by Django 2.0.2 on 2021-04-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendSite', '0002_auto_20210303_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='mobile_view_image',
            field=models.FileField(blank=True, default='image_not_found.jpg', max_length=255, null=True, upload_to='slider/mobile_view_slider/'),
        ),
    ]
