# Generated by Django 2.0.6 on 2018-08-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0006_delete_customcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=10, verbose_name='Mobile Number')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Service Orders',
                'verbose_name_plural': 'All Service Orders',
            },
        ),
    ]
