# Generated by Django 2.0.2 on 2020-12-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceOrders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorders',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorders',
            name='booking_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorders',
            name='booking_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
